lux/compiler/Compiler.py, tests/test_compiler.py
Adding code in Complier.py that adds a step for removing invalid views during view collection generation(ex. year by year). Adding old test cases back to test_compile.py and adding showMore calls to the test cases.
=> Adding logic for removing invalid views in compiler, and updated compiler tests. 

doc/source/reference/gen/lux.compiler.Validator.Validator.rst, doc/source/reference/gen/lux.luxDataFrame.LuxDataframe.LuxDataFrame.rst, examples/tutorial/5-datetime.ipynb, lux/action/column_group.py, lux/action/row_group.py, lux/action/univariate.py, lux/compiler/Compiler.py, lux/compiler/Validator.py, lux/data/stocks.csv, lux/executor/PandasExecutor.py, lux/luxDataFrame/LuxDataframe.py, lux/utils/date_utils.py, lux/vis/Vis.py, lux/vis/VisList.py, requirements.txt, tests/test_action.py, tests/test_compiler.py, tests/test_dates.py, tests/test_display.py, tests/test_executor.py, tests/test_interestingness.py, tests/test_parser.py, tests/test_vis.py
Refactored LuxDataFrame implementation to avoid metadata computation in `__init__` since internal Pandas calls were causing unnecessary computation and slowdown. Metadata is no longer computed at dataframe creation and only computed at display time (and memorized). Metadata is invalidated when there is an in-place Pandas operation. Some preliminary performance results are shown here:
=> Refactor LuxDataframe for more efficient metadata and recommendation maintenance

lux/core/frame.py, lux/executor/PandasExecutor.py, tests/test_action.py, tests/test_pandas_coverage.py
This pull request fixes issues that cause Lux to error when a column of DataFrame has the `dtype` set to something non-standard (eg. `uint8` or `Int64`). This would relax the condition that a column of integers had to be `int64`; now it can be a column of integers of any size (unsigned or signed).
Also, after studying how Pandas internal functions are called and how often, we decided to expire the metadata almost exclusively inside `getattr` and remove other places of metadata expiration.
However, we also end up expiring the metadata in `_set_axis`. This fixes the bug where the metadata with new column names is propagated after it's renamed with this technique: 
```python
df.columns =  ["col1", "col2", "col3", "col4","col5", "col6", "col7", "col8", "col9", "col10"]
```
Finally, tests for …
=> Fix bugs relating to dtype and metadata propagation

lux/core/frame.py, lux/executor/PandasExecutor.py
The df.sample operation is fairly expensive and occupies a large percentage of the runtime. 
We memoize any unfiltered samples generated for the dataframe in order to speed up the recommendations. This avoids many repetitive computation to sample for every visualizations. We only operate on unfiltered samples since the filter step occurs before sampling, so the input dataframe would be different. This yields a few seconds of improvement in runtime for generating the Lux display:
- Airbnb [244475 rows x 12 cols] : 19.29s → 18.14 s
- Flights [855632 rows x 11 cols]:  21.24s → 18.80s
=> memoize unfiltered sample

examples/demo/college_demo.ipynb, lux/core/frame.py, lux/vislib/altair/AltairChart.py, lux/vislib/altair/BarChart.py, tests/test_pandas_coverage.py, tests/test_vis.py
This PR solves #108 where the text attribute was getting overridden by the encoding color. Since encoding takes priority over any attributes we set on the chart, the fix, as recommended by https://github.com/altair-viz/altair/issues/1033 is to encode the chart separately from the text. I overrode the `encode_color()` method in `BarChart.py` by adding the text after the encoding. All other graphs behave the same way.
=> Encode color of chart before adding text

lux/executor/PandasExecutor.py, tests/test_type.py
Merged master branch, cleaned up temporal detection, added test cases.
=> Updated temporal detection and tests

lux/action/filter.py, lux/core/__init__.py, lux/core/series.py, lux/executor/PandasExecutor.py, lux/interestingness/interestingness.py, lux/processor/Validator.py, lux/utils/utils.py, lux/vislib/altair/LineChart.py, tests/test_interestingness.py, tests/test_nan.py, tests/test_type.py
This PR fixes some of the issues around missing values and NaNs. This has been tested on the sample dataset in #179 and  [this Kaggle dataset](https://www.kaggle.com/c/kaggle-survey-2020/data). 
Included in this PR: 
- Handling NaN values in processing: 
* skipping validator check for NaN filter values
* adding special case for PandasExecutor to map filter NaN to isna() 
* fixing unevenness metric when bar values are NaN
* improve type checking for NaN columns coerced to floats
* exclude NaN for line charts to prevent large axes offsetting
- Displaying NaN values in bar charts: 
* ensure that NaNs are not dropped in groupbys inside PandasExecutor
* exclude NaN values in deviation calculation
- Better datetime warning message with starter code template
- Additions to LuxSeries:
* fix …
=> Making Lux more robust with missing values and NaN (#179)

lux/action/filter.py, lux/action/univariate.py, lux/core/frame.py, lux/core/series.py, lux/executor/Executor.py, lux/executor/PandasExecutor.py, lux/processor/Compiler.py, lux/utils/date_utils.py, tests/test_dates.py, tests/test_nan.py, tests/test_pandas_coverage.py, tests/test_performance.py, tests/test_type.py
This PR standardizes data_type attributes into data_type_lookup and implements methods to compute data_type_lookup, data_model, and data_model_lookup
=> Coalesce all data_type attributes of frame into one

lux/core/frame.py, lux/core/series.py, lux/executor/PandasExecutor.py, tests/test_nan.py, tests/test_pandas.py, tests/test_series.py
Concat-based operations led to some bugs in `df.describe`, `df.convert_dtypes` and `df.as_type`. 
This seems to be a result of the metadata propagation patch, in particular, this line:
```python
f._get_axis_number = super(LuxSeries, self)._get_axis_number
```
originally implemented based on [this comment](https://github.com/pandas-dev/pandas/issues/13208#issuecomment-326556232). It seems like there have been some [updates to instructions to subclass Series](https://pandas.pydata.org/pandas-docs/stable/development/extending.html#subclassing-pandas-data-structures) and metadata is automatically propagated over(?)
@westernguy2 : It would be useful to check if this PR doesn't break any of the Series metadata propagation that you were working on, as it doesn't seem to be well covered by …
=> Series Bugfix for describe and convert_dtypes

lux/executor/PandasExecutor.py, lux/interestingness/interestingness.py, tests/test_config.py, tests/test_dates.py, tests/test_interestingness.py
Rewrote the following code which was slowing down `t_rec`: 
- remove sampling in `is_datetime_string`, since sampling was slower than no sampling (425ms --> 480ms)
- changed `scipy.stats.spearmanr` to `scipy.stats.pearsonr`(360ms --> 2.2ms, huge performance gain!)
Overall, with these changes the 1st print time for 1 million datapoints on Airbnb (12 cols, no sampling) went from around 6.5sec down to around 3.8, so around 1.8x faster.
=> Performance optimization on recommendation compute

lux/executor/PandasExecutor.py, tests/test_type.py
Closes #218 by adding a datetime validator, `_is_datetime_number(series)`, which takes in a series, checks if it's numerical, and outputs whether the numerical values (e.g. year, date) can be interpreted as datetimes. 
- It does so without the need for Regex, by using the Pandas built-in `to_datetime()` function which raises an exception if the input is likely, not interpretable as a datetime (e.g. year is way past the current date, the number is negative). 
- Numerical values representing the day of the week or month of the year are currently not interpreted as a temporal type unless the column name is "day" or "month". The argument here is that it's difficult to conclude that such a common range of values (e.g 1 - 30) are absolutely temporal.  
- Implementation for …
=> Temporal type detection for integers via PandasExecutor._is_datetime_number

lux/core/frame.py, lux/executor/PandasExecutor.py
Before, the user could change `df.data_type` by setting it to some other dictionary. This would benefit from being a "protected variable". Thus, `df.data_type` is a property getter for `df._data_type`. 
Also, `df.data_type` only returned a non-null dictionary if `df._repr_html()` was called before. Now, the getter calls `df.maintain_metadata()` if `df._data_type` is null.
Changed:
- changed metadata attribute `df.data_type` to `df._data_type`
- added a getter that calls `df.maintain_metadata` if `df._data_type` is NULL
=> [PATCH] Make df.data_type a property that accesses df._data_type

lux/core/series.py, tests/test_interestingness.py, tests/test_series.py, tests/test_vis.py
Added additional property for recommendation VisList in LuxSeries, mimics frame object functionalities for recommendation
=> Add recommendation property to LuxSeries objects

lux/executor/SQLExecutor.py, tests/test_compiler.py, tests/test_sql_executor.py
Added filtering out of null values in all SQL queries
Fixed issue where binning would fail with integer type variables
=> Bug Fixes in Histogram Binning

lux/core/frame.py, tests/test_action.py
Improve expire recommendation strategy so that current_vis does not expire when the recommendations expire in `expire_recs`. The `current_vis` only changes when the intent is set explicitly. In the test example, when a Pandas write operation is performed, the recommendations are expired, but the `current_vis` is unchanged.
=> Prevent current_vis from expiring upon Pandas write operations

requirements.txt
This PR updates the requirement for the Pandas package to 1.2.0. Otherwise, it causes an unexpected error in `pd.crosstab` and does not accurately create the right visualizations.
=> [PATCH] Require Pandas 1.2.0

lux/executor/SQLExecutor.py, tests/test_sql_executor.py
Updated SQLExecutor 2D binning aggregation. Previously relied on using multiple width_bucket queries to generate heatmap data, but this caused extensive overhead and was slow. The new method is able to do the same aggregation via a single query which has reduced the querying overhead.
=> Optimizing SQLExecutor Heatmap Aggregation

lux/core/frame.py, lux/core/series.py, tests/test_compiler.py, tests/test_error_warning.py
This PR allows the backend to send messages to the frontend API to be displayed as warnings rather than using UserWarnings which do not comply with Pandas Style.
So far, the only case when no recommendations are shown is when none of the default actions can be completed because the data has too few data points.
- actions only computed if length of df > 0
- `_data_type` set to {} instead of `None` to enable fetching from an empty dictionary
- appropriate error messages added
- removed Pandas fallback
- adjust some series condition checks
=> Display better warnings when no recommendations are generated

lux/__init__.py, lux/core/frame.py, lux/core/sqltable.py, lux/executor/SQLExecutor.py, tests/test_compiler.py, tests/test_sql_executor.py
Created the LuxSQLTable object to differentiate between Lux' pandas and SQL functionality.
Users can create a LuxSQLTable object and specify which table they would like to connect the object to within the constructor. All of Lux' recommendation functionality is still available, but users will not be able to perform pandas operations on the object as no data is stored locally.
The new object is within the sqltable.py file and inherits all of Lux' recommendation system functionality from the LuxDataFrame object. The set_SQL_table() function has also been moved from the LuxDataFrame object to the LuxSQLTable object as we now expect users to not connect dataframes to their databases anymore.
In addition to the new LuxSQLTable changes, the corresponding test files in the test suite have been …
=> Created LuxSQLTable Object

lux/vislib/altair/Choropleth.py
Previously, choropleth visualizations would not appear when `x_attr` or `y_attr` was abbreviated. With this change, all choropleth visualizations should appear as expected. 
- Modifications in `vislib/altair/Choropleth.py`
Now, when we run 
```
import pandas as pd
import lux
df = pd.read_csv("https://raw.githubusercontent.com/lux-org/lux-datasets/master/data/hpi.csv")
df
```
we should get the following output with no empty visualizations.
=> Resolve empty vis bug for geographic data types

lux/core/frame.py, lux/core/series.py, lux/vis/Vis.py, lux/vis/VisList.py, tests/test_action.py, tests/test_compiler.py, tests/test_config.py, tests/test_dates.py, tests/test_display.py, tests/test_error_warning.py, tests/test_groupby.py, tests/test_interestingness.py, tests/test_maintainence.py, tests/test_nan.py, tests/test_pandas.py, tests/test_pandas_coverage.py, tests/test_parser.py, tests/test_performance.py, tests/test_series.py, tests/test_type.py, tests/test_vis.py
The widget display used to be displayed before Out[...], which is not in accordance to what Pandas usually does. This PR moves the widget to Out[...] in IPython notebooks. This PR addresses both #56 and #60
I replaced `_repr_html_` with `_ipython_display_` in both `frame.py` and `vis.py`. I then removed `__repr__` from `frame.py` so that it uses the Pandas default `__repr__` when the widget isn't displayed. I added a test to ensure this is the case.
Below is an example of the widget showing up in Out[...]. Notice that Out[...] doesn't show up below the widget, which means the widget is actually in Out[...]
=> Move widget display to `Out[...]`

lux/core/frame.py
Currently the Pandas methods that are being overridden (`head`, `tail`, `describe`) are changing the history for the original DataFrame, instead of the newly created one. This PR fixes that issue.
The PR moves changes the metadata of the DataFrame returned as a result of the Pandas operation. It also removes method that extends `info` since `info` doesn't return a DataFrame. The PR also ensures that the `_pandas_only` flag works in `_ipython_display_` by re-adding the else clause that was commented out.
The bug where two DataFrames would be outputted as a result of the lines:
```python
df.info()
df
```
was what flagged this issue, and this is now fixed.
=> Fix Metadata Propagation with Overridden Pandas Methods

lux/action/correlation.py, lux/action/univariate.py, lux/core/frame.py, lux/core/sqltable.py, lux/executor/PandasExecutor.py, lux/executor/SQLExecutor.py, lux/interestingness/interestingness.py, lux/utils/utils.py
Added __len__() function capability to the LuxSQLTable and updated metadata handling.
Made changes to the LuxSQLTable to enable `len(sql_tbl)` functionality. Updated references to the `sql_tbl._length` parameter throughout the code to be replaced by `len(sql_tbl)`. Making these changes also required updating the metadata calculation process for the LuxSQLTable. 
During the initial setup of the LuxSQLTable, it needs to have the same `len()` functionality as the LuxDataFrame. Added a boolean parameter to keep track of which part of setup a LuxSQLTable is in, and this informs `len()` to either return `sql_tbl._length` or the parent class' `len()`.
=> Update LuxSQLTable __len__() and metadata computation""

lux/action/correlation.py, lux/action/univariate.py, lux/core/frame.py, lux/core/sqltable.py, lux/executor/PandasExecutor.py, lux/executor/SQLExecutor.py, lux/interestingness/interestingness.py, lux/utils/utils.py
Merging in master branch changes from PRs #326 and #332
=> Merging in Master branch changes to sql-engine branch

lux/executor/PandasExecutor.py, tests/test_interestingness.py, tests/test_pandas_coverage.py
Fixing various bugs and inconsistent logic in data type inference.
* remove unnecessary convert_dtype in float inference (previously added to make integer columns with NaNs detectable as floats, now switch to cardinality cutoff for all)
* bring back cardinality calculation on all float columns (removing the need for special value 999 on float cardinality)
* nominal detection applies even for floats < 20 rows (and associated test changes)
=> Bugfix in test and data type inference code

lux/vislib/matplotlib/ScatterChart.py
For matplotlib scatterplots, the figsize was inputted in the argument of `plt.subplot`, resulting in a `ValueError` when the exported code was run. I fixed this error by moving the width and height arguments to the subplot's `figsize` property.
=> Matplotlib Export Bug for Scatterplot

lux/action/univariate.py, lux/vislib/altair/Choropleth.py, lux/vislib/matplotlib/MatplotlibRenderer.py, tests/test_vis.py
In this PR, we call upon the AltairRenderer and inform users that the choropleths are rendered via the Altair backend when users set their backend to Matplotlib and geographic attributes are detected. 
- If enough users indicate interest in choropleth rendering via matplotlib, we will reopen #310. 
- **Rationale**: Matplotlib doesn't support choropleths out of the box. It would require some [third party library](https://matplotlib.org/stable/thirdpartypackages/index.html#mapping-toolkits) such as Cartopy or Geopandas. While these libraries meet the necessary requirements to add Matplotlib support for choropleths, they are expensive (Cartopy is 14.6 MB, GeoPandas depends on Fiona which is 49 MB). 
Closes #310. 
- Additional code in `MatplotlibRendererer.py`
- Quick modification of repr …
=> Support choropleths for Matplotlib backend via Altair 

lux/executor/PandasExecutor.py, lux/utils/utils.py, requirements-dev.txt, tests/test_nan.py
Closes #249
I've noticed that we have a type deduction error in case the field had NaNs as described in the attached issue.
I furthur noticed that we don't check if the string columns can be casted to a float/int type. I've added extra check to see id a string column can be casted to an int/float column and deduce the proper data_type accordingly.
Update (04/10/2021)
* Adding warning message when NaN columns displayed as histograms
* Resolve NaN series causing error in histogram `execute_binning`
* Rewrote `is_numeric_nan_column` to run 2x faster
I've added a logic to 
1. Check if the column can be cast to int/double
2. apply the respective data_type inference.
The result shows that the two columns mentioned in the issue: `# Instances` and `# Attributes` have a correct data_type now
=> [WIP] update type inference for string columns

.github/workflows/python-app.yml, Makefile, tests/test_compiler.py, tests/test_interestingness.py, tests/test_sql_interestingness.py, tests/test_type.py, tests_sql/__init__.py, tests_sql/conftest.py, tests_sql/context.py, tests_sql/test_sql_compiler.py, tests_sql/test_sql_executor.py, tests_sql/test_sql_interestingness.py
Separated and moved the SQLExecutor tests to the `tests_sql` folder. 
- Created new test files within the tests_sql folder to test the Lux SQL functionality.
- Updated the make file to include a command to test both the pandas and SQL functionalities.
- Updated the Github workflow to also run the tests_sql folder
=> Separate Pandas and SQL test suite

lux/action/enhance.py, lux/action/filter.py, lux/core/frame.py, lux/vis/Vis.py, lux/vislib/matplotlib/ScatterChart.py, tests/test_nan.py, tests/test_vis.py
Current-vis: "All-column" vis when only few columns in dataframe #199
If dataframe has only 2 or 3 columns, use current_vis to show an all-column visualization
=> "All-column" vis when only few columns in dataframe #199

lux/_config/config.py, lux/core/frame.py, lux/core/series.py, lux/executor/Executor.py, lux/executor/PandasExecutor.py, lux/executor/SQLExecutor.py, lux/interestingness/interestingness.py, lux/processor/Compiler.py, lux/vis/Vis.py, lux/vis/VisList.py, lux/vislib/altair/AltairRenderer.py, requirements-dev.txt, tests/test_action.py, tests/test_config.py, tests/test_performance.py
Incorporating early pruning optimizations described in [our recent paper](http://dorisjunglinlee.com/files/lux-vldb-tr.pdf) to speed up cases where the visualization search space is large (e.g., VisList contains more than top K visualizations and the dataframe has a large number of rows).
- Adding in `execute_approx_sample` for approximating samples for early pruning
- Apply early pruning based on empirically-tested width and length criteria
- Added tests and warning messages when early pruning conditions are met
Others: 
- Increasing the sampling start and cap for overall sampling
- Adding config flag to turn lazy maintenance on/off
- Added cached method for `df.unique()`
Here are some results from preliminary experiments on the 1M Airbnb dataset. We duplicate a single visualization N …
=> Scalability: incorporate early pruning optimizations

lux/core/frame.py, lux/processor/Compiler.py, lux/vislib/altair/BarChart.py, lux/vislib/altair/LineChart.py, tests/test_series.py
Several bugfixes for the new COVID HPI demo:
* For all column vis, display only if more than one column (i.e., not series), since visualization is a duplicate of series vis
* Before: 
* After:
* For temporal, when there is only a single data point for a date, display a single bar instead of a line chart, since it is not possible to display a line chart with only a single data point. 
* Before: 
* After:
=> Bugfix for all column and temporal action

.github/workflows/python-app.yml, doc/source/guide/export.rst, lux/core/frame.py
Minor changes to enable integration with interactive data reports (Streamlit, DataPane)
- Added return HTML option to `save_as_html`
- reorganize and updated documentation for export
- added new documentation for export to DataPane and Streamlit
- Temporary `pip install git+git://github.com/lux-org/lux-widget.git` fix based on #372
=> New functionality and docs for export to data reports

lux/vislib/altair/Choropleth.py, requirements.txt
Remove [python-us](https://github.com/unitedstates/python-us) dependency due to dependency errors on the [lux-api conda feedstock](https://github.com/conda-forge/lux-api-feedstock) ([python-us:56](https://github.com/unitedstates/python-us/issues/56)).
=> Remove python-us dependency

lux/executor/PandasExecutor.py, tests/test_performance.py
This PR fixes the issue of multiple warnings for temporal columns in #370. The problem originates from the bugfix introduced in  #297, leading to a side effect where `vis.data.clear_intent()` triggers `set_intent` which recomputes the cleared metadata.
- The intent is now cleared through private access, instead of via setter. This also speeds up the visualization generation since metadata is not being recomputed multiple times.
- Minor rewrite of warning message and test
=> Fix temporal warning displayed multiple times

lux/core/frame.py, lux/core/groupby.py, tests/test_pandas.py
This PR fixes the issue in #382 for `df.groupby("some_column")["some_other_column"].describe()`.
It also deactivates the disabled Lux display for `df.describe` to ensure consistency with other Pandas APIs.
=> Bugfix LuxSeriesGroupBy apply

lux/vislib/matplotlib/BarChart.py, lux/vislib/matplotlib/LineChart.py, lux/vislib/matplotlib/ScatterChart.py, tests/test_vis.py
This PR fixes the issue in #380. In addition, this PR includes several fixes to matplotlib code exports.
=> KeyError bugfix for matplotlib bar chart

lux/vislib/altair/AltairChart.py, lux/vislib/altair/Choropleth.py
@cjachekang reported an issue with integer type geographic columns, as shown in the [communities dataset](https://github.com/lux-org/lux-datasets/blob/master/data/communities.csv).
This PR fixes the issue and displays the integer state columns based on their FIPS directly.
In addition, this PR also increases the width of choropleth charts so that the visualizations don't appear to be too squished horizontally.
=> Fixing to Choropleth width and int type error

.github/workflows/python-app.yml, lux/vislib/matplotlib/LineChart.py, requirements.txt
closes #396
also temporary fix for #398
=> added timestamp import to matplotlib linecharts (#396)

doc/source/reference/config.rst, doc/source/reference/gen/lux._config.config.Config.rst, lux/_config/config.py, lux/vislib/altair/BarChart.py, lux/vislib/matplotlib/BarChart.py
Resolves issue #408. In addition adds the ability to set display axis label lengths.
Changes made to altair and matplotlib bar chart specifications, as well as configuration. 
Should allow users to set number of bars in bar charts, and change default max axis label lengths.
=> Additional configuration options for number of bars and axis labels

lux/core/__init__.py, requirements.txt, tests/test_action.py, tests/test_groupby.py, tests/test_maintainence.py, tests/test_performance.py
Signed-off-by: Kunal Agarwal <kagarwal2@berkeley.edu>
Pandas 1.3.x changes the file structure of `pd.io.parsers`. As a result, in order to read any data in as a LuxDataFrame, the following change must be made.
I've changed `__init__` to account for the new file structure mentioned above. I've also updated the requirements to require `pandas>= 1.3.0` since the change will cause Lux to break on any Pandas version below 1.3.0.
Currently 3 tests are failing due to a different update in Pandas 1.3.x which causing history to not propagate in some instances.
The example given in #398 displays the Lux widget as expected now.
=> FIX-#398: Add fix for pandas 1.3

.github/workflows/python-app.yml, .pre-commit-config.yaml, CONTRIBUTING.md, pyproject.toml, requirements-dev.txt
Signed-off-by: Cristian Garcia <cgarcia.e88@gmail.com>
Introduces `pre-commit` hooks, this will run `black` on each commit if you have it installed, it can also be configured to run other things like `isort` in the future.
* Adds the `pre-commit` dependency.
* Changes CI to use `pre-commit` and deletes the `black` step.
* Updates `CONTRIBUTING.md` with info on how to install and run `pre-commit`.
=> Adds pre-commit hooks

lux/executor/PandasExecutor.py, tests/test_pandas.py
Signed-off-by: Cristian Garcia <cgarcia.e88@gmail.com>
Fixes #440 by replacing `inf`s with `nan`s.
Uses 
```python
vis._vis_data = vis._vis_data.replace([np.inf, -np.inf], np.nan)
```
inside `PandasExecutor.py` on several places to remove `inf`s.
=> Replace infs with nans to avoid crash when creating a heatmap

tests/test_pandas.py
Issue #417 suggest datetime index after de-serialization might cause issues, however the error was not reproducible by the added tests.
* Adds two tests with dataframes that have datetime indexes.
=> FIX-#417: Add test for datetime index

lux/executor/PandasExecutor.py, lux/utils/date_utils.py, lux/vislib/altair/AltairChart.py, tests/test_pandas.py
Fixes #419 by handling `timedelta64` columns in `sanitize_dataframe`.
* Adds tests for the `timedelta64` and `interval` dtypes.
* Converts `timedelta64` columns to `dt.seconds` inside the `sanitize_dataframe` function.
=> FIX-#419: Handle incompatibility issues between timedelta64 dtypes with Altair

README.md
Its not a full solution for wrong installations but having a small note at the beginning of the Getting Started that guides users to correctly installing `lux-api` instead of `lux` and informing/reminding them they need to install the jupyter extension might help on this regard.
=> DOCS-#447: Add note about installation and setup in README

lux/core/series.py, lux/executor/PandasExecutor.py, tests/test_pandas.py
Mixed dtype columns cause `execute_2D_binning` to crash when trying to bin via `pd.cut`, this error shows up frequently in users code (#403, #394).
* Adds a test using mixed dtypes
* Tries to cast series to `float` inside `execute_2D_binning`
=> FIX-#403: Fixes mixed-dtype problem in execute_2D_binning

lux/__init__.py, lux/utils/debug_utils.py, tests/test_utils.py
Adds a `show_versions()` function that prints the lux, pandas, and luxwidget versions. We can ask for this information for debugging.
=> FIX-#447: Add show_versions helper for debugging

.github/ISSUE_TEMPLATE/bug_report.md, lux/__init__.py, lux/utils/debug_utils.py, requirements.txt, tests/test_utils.py
Per #447, add some debug information (i.e. a warning) in case `luxwidget` is not installed/enabled.
=> FIX-#447: Add debug information if luxwidget extension is not enabled.

.github/workflows/python-app.yml
Edit CI workflow to commit lint checks if first commit message is formatted correctly.
=> FIX-#462: Commit Lint only checks first commit

lux/vislib/altair/AltairChart.py, lux/vislib/matplotlib/MatplotlibChart.py, tests/test_vis.py
Signed-off-by: Labanya Mukhopadhyay <labanya@ponder.io>
If a title is longer than 25 characters (due to a long filter value), it is abbreviated so the visualization is not exceedingly wide or have a title that is cut off. Referencing https://github.com/lux-org/lux/issues/298
The long text is truncated in both Altair and Matplotlib charts so that chart_title = chart_title[:15] + "..." + chart_title[-10:].
tests/test_vis.py also includes test_abbrev_title to test for this behavior.
=> FIX-#298: Abbrev long filter values and add to vis test

doc/conf.py, requirements.txt
Signed-off-by: Labanya Mukhopadhyay <labanya@ponder.io>
Addresses Issue #464.
Removed the sh dependency in requirements.txt and its usage in doc/conf.py: `subprocess.call(["sh", "./docbuild.sh"])`.
=> FIX-#464: Remove sh dependency

lux/core/__init__.py, lux/core/frame.py, lux/core/groupby.py, lux/core/series.py, lux/executor/PandasExecutor.py, tests/test_zexport.py
After this refactor, Making `Vis` etc support the pandas library is as easy as defining 4 1-liner classes.
For example, for modin defining this one-liner class is enough for it to be used with `Vis`:
```python
class LuxModinDF(LuxDataFrameMixin, modin.DataFrame): pass
```
then wrap the dataframe `df` by:
```python
df = LuxModinDF(df)
```
I refactored Lux's pandas subclasses into mixins and thin wrappers using mixins (much like the above one liner).
No change.
=> FEAT-#493: Extensible.
