docs/conf.py
Doesn't include build scripts (still in progress). Simple styling change before I forget.
=> doc styling

lux/vizLib/altair/Histogram.py
=> Mark_bar for histogram based on range of plot ratio

examples/postBuild
postBuild script -- testing to see if this is the proper way to install npm. Not sure if it will make a difference but testing anyway to be exhaustive.
=> Create postBuild for binder

lux/executor/SQLExecutor.py
Current version of SQL Executor
=> Added Sum and Max aggregate functionality to SQL Executor

examples/DatetimeDemo.ipynb, lux/luxDataFrame/LuxDataframe.py, lux/view/View.py, lux/view/ViewCollection.py, tests/test_dates.py
Also added a test that tests this issue, and fixed output for DatetimeDemo notebook.
=> Extend __setitem__ to ensure metadata gets refreshed for inplace changes

lux/luxDataFrame/LuxDataframe.py
=> Make Current View vis exportable (and larger in size)

lux/vis/Vis.py, tests/test_action.py
Added in test for generalize action in test_action
=> Update Generalize Action Bug Fix to fit new API

examples/tutorial/1-specifying-intent.ipynb, lux/action/generalize.py, lux/core/frame.py, lux/processor/Compiler.py, lux/vis/Vis.py, lux/vis/VisList.py, tests/test_action.py, tests/test_compiler.py, tests/test_interestingness.py, tests/test_vis.py
- fixed bug for VisList refresh on List[Vis] input
- fixed bug for subsequent df display
- Added test and other minor bug fix and changes
=> Refactor VisList on List[Vis] input

doc/requirements.txt
=> add package information to requirements

lux/core/frame.py, lux/executor/Executor.py, lux/executor/PandasExecutor.py
Fixed test case test_prefix in pandas_coverage function, 1_year variable that was created was not getting it's data type computed
=> Moved Metadata functions to Executors, resolved issue in test_prefix case

lux/core/frame.py, lux/executor/PandasExecutor.py, tests/test_pandas_coverage.py, tests/test_performance.py, tests/test_type.py
=> minor fixes

.gitignore, lux/core/frame.py, tests/conftest.py, tests/test_action.py, tests/test_compiler.py, tests/test_config.py, tests/test_dates.py, tests/test_display.py, tests/test_error_warning.py, tests/test_executor.py, tests/test_interestingness.py, tests/test_maintainence.py, tests/test_nan.py, tests/test_pandas.py, tests/test_pandas_coverage.py, tests/test_parser.py, tests/test_performance.py, tests/test_type.py, tests/test_vis.py
using pytest fixture global shared variable in test
=> Global shared variable in test (#144)

doc/source/reference/config.rst
Add a table of contents for config page in the documentation. #245
=> Table of contents for config page

lux/core/sqltable.py, tests/test_vis.py
Reformatting recently changed files using Black
=> Black Reformatting

lux/action/univariate.py, lux/executor/PandasExecutor.py, lux/utils/utils.py, lux/vislib/altair/Choropleth.py, lux/vislib/matplotlib/MatplotlibRenderer.py, lux/vislib/matplotlib/ScatterChart.py, requirements-dev.txt, tests/test_interestingness.py, tests/test_nan.py, tests/test_pandas_coverage.py, tests/test_vis.py
Merging in latest master branch changes from PRs #322, #343, and #349.
=> Merging in master branch changes

doc/source/advanced/executor.rst
Added documentation and instructions for SQL Executor. 
Additional details, terms and GIFs added for SQL Execution Engine.
=> Sql Executor documentation

lux/executor/Executor.py, lux/processor/Compiler.py, tests/test_nan.py
=> Empty dataframe data type error (#376)

.github/pull_request_template.md, .github/workflows/python-app.yml, CONTRIBUTING.md, commitlint.config.js
Signed-off-by: Doris Lee <dorisjunglinlee@gmail.com>
=> DOCS-#421: Add commit message guideline and lint check

README.md
Signed-off-by: Doris Lee <dorisjunglinlee@gmail.com>
=> DOCS-#452: Fix link to ZQL in README

doc/source/guide/FAQ.rst, doc/source/reference/gen/lux._config.config.Config.rst, doc/source/reference/gen/lux.core.frame.LuxDataFrame.rst, doc/source/reference/gen/lux.core.series.LuxSeries.rst, doc/source/reference/gen/lux.executor.Executor.Executor.rst, lux/utils/debug_utils.py
Addresses [https://github.com/lux-org/lux/issues/458](url)
Added documentation to explain the output of debug_info. Also added checker to insure lux-api library is installed and if lux needs to be upgraded to a higher version.
=> FIX-#458:Add doc for debug_info and checker for lux version
